name: dsci-532-dashboard
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - geopandas
  - altair
  - vega_datasets
  - vl-convert-python
  - shiny
  - shinywidgets 
  - ipyleaflet    
  - ipykernel
  - jupyterlab
  - notebook
  - ruff
  - tabulate
  - anywidget
  - pip

  - pip:
      - querychat==0.5.1
      - chatlas==0.15.2
      - python-dotenv==0.9.9
