name: dsci-532-dashboard
channels:
  - conda-forge
dependencies:
  - numpy
  - ipykernel
  - flask
  - vega_datasets
  - altair
  - plotly
  - dash
  - ruff
  - notebook
  - pandas
  - python=3.11
  - jupyterlab
  - black
  - vl-convert-python
  - tabulate
  - shiny
  - matplotlib
  - scipy